import { COLORS, FONT_SIZE } from "../../../src/constants/tema.js"

const styles = {
  scroll: {
    backgroundColor: COLORS.branco,
  },
  container: {
    padding: 20,
    flex: 1,
    backgroundColor: COLORS.branco,
    alignItems: "center",
  },
  search: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#ddd",
    marginBottom: 20,
    width: "100%",
  },
  grafico: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 20,
    width: "100%",
    padding: 10,
  },
  graficoText: {
    textAlign: "center",
    fontSize: FONT_SIZE.md2,
    fontWeight: "bold",
    marginBottom: 10,
    color: COLORS.marrom,
  },
  touchable: {
    width: "100%",
    height: 150,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  graficoImg: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
    backgroundColor: COLORS.marrom,
    borderRadius: 10,
  },
  graficoText2: {
    position: "absolute",
    bottom: 5,
    left: 8,
    color: COLORS.marromClaro,
    fontSize: FONT_SIZE.sm,
    padding: 3,
    fontWeight: "bold",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 8,
  },
  containerPrat: {
    backgroundColor: COLORS.branco,
    alignItems: "center",
    justifyContent: "center,",
  },
  estantes: {
    flexDirection: "column",
    padding: 10,
    marginBottom: 20,
  },
  itemContainer: {
    width: "85%",
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    borderWidth: 1,
    borderColor: COLORS.cinzaEscuro,
    borderRadius: 8,
    backgroundColor: COLORS.branco,
    marginBottom: 10,
    gap: 5,
  },
  itemImage: {
    width: 60,
    height: 60,
    marginRight: 10,
    borderRadius: 8,
    backgroundColor: COLORS.cinzaEscuro,
  },
  textContainer: {
    flex: 1,
  },
  itemTitle: {
    fontSize: FONT_SIZE.md,
    fontWeight: "bold",
    color: COLORS.marrom,
  },
  itemDescription: {
    width: "100%",
    fontSize: FONT_SIZE.xsm,
    color: COLORS.cinzaEscuro,
  },
  pratHeader: {
    color: COLORS.marrom,
    fontSize: FONT_SIZE.md2,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
  },
  popupButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.marrom,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)", 
  },
  modalContent: {
    width: "80%", 
    backgroundColor: COLORS.branco, 
    padding: 20, 
    borderRadius: 10, 
    alignItems: "center", 
  },
  inputField: {
    width: "100%",
    padding: 10,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: COLORS.marrom,
    borderRadius: 5,
    backgroundColor: COLORS.branco,
  },
  closeButtonText: {
    fontSize: FONT_SIZE.md,
    color: COLORS.marrom,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 20,
  },
  modalTitle: {
    fontSize: FONT_SIZE.md2,
    fontWeight: "bold",
    color: COLORS.marrom,
    marginBottom: 15,
  },
}

export default styles
