import { StyleSheet } from "react-native"
import { COLORS, FONT_SIZE } from "../../constants/tema"

const styles = StyleSheet.create({
  container: {
    width: "100%",
    flex: 1,
    paddingVertical: 20,
    paddingTop: 60,
    alignItems: "stretch",
    backgroundColor: COLORS.branco,
  },
  scroll: {
    paddingVertical: 10,
    backgroundColor: COLORS.branco,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  line: {
    width: "80%",
    borderColor: COLORS.marrom,
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 1,
    marginBottom: 10,
    alignSelf: "center",
  },
  lineT: {
    fontSize: FONT_SIZE.md2,
    color: COLORS.marromClaro,
  },
  name: {
    fontSize: FONT_SIZE.lg,
    fontWeight: "800",
    color: COLORS.azulEscuro,
  },
  boxInfo: {
    width: "90%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.marrom,
    padding: 10,
    borderRadius: 15,
  },
  textContainer: {
    flex: 1,
    paddingHorizontal: 10,
  },
  text: {
    fontSize: FONT_SIZE.md,
    fontWeight: "bold",
    color: COLORS.branco,
  },
  description: {
    width: "100%",
    fontSize: FONT_SIZE.xsm,
    color: COLORS.branco,
  },
  text2: {
    fontSize: FONT_SIZE.sm,
    fontWeight: "400",
    color: COLORS.branco,
  },
  iconLeft: {
    marginRight: 2,
  },
  iconRight: {
    marginLeft: 2,
  },
  infoEstante: {
    width: "90%",
    backgroundColor: COLORS.branco,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.linho,
    padding: 15,
    gap: 10,
    justifyContent: "center",
    position: "absolute",
    top: "20%",
    borderLeftWidth: 5,
  },
  title: {
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    backgroundColor: COLORS.linho,
    borderRadius: 5,
  },
  textTitle: {
    paddingLeft: 10,
    fontSize: FONT_SIZE.md2,
    color: COLORS.marrom,
    fontWeight: "700",
  },
  closeButton: {
    padding: 7,
    borderRadius: 50,
  },
  textWrapper: {
    paddingLeft: 10,
    flexDirection: "row",
    marginBottom: 5,
    width: "100%",
    backgroundColor: COLORS.cinzaClaro,
    borderRadius: 5,
    padding: 5,
    alignItems: "center",
    justifyContent: "space-between",
  },
  textM: {
    fontSize: FONT_SIZE.md,
    fontWeight: "700",
    color: COLORS.marromClaro,
    flex: 1,
    marginRight: 10,
  },
  labelText: {
    fontSize: FONT_SIZE.md,
    fontWeight: "700",
    color: COLORS.marrom,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 15,
    width: "100%",
  },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.amarelo,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    flex: 1,
    marginRight: 5,
    justifyContent: "center",
  },
  deleteButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.vermelho,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    flex: 1,
    marginLeft: 5,
    justifyContent: "center",
  },
  buttonText: {
    color: COLORS.branco,
    fontWeight: "bold",
    fontSize: FONT_SIZE.md,
    marginLeft: 8,
  },
  popupButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.marrom,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
})

export default styles
