import { StyleSheet } from "react-native";
import { COLORS } from "../../../constants/tema";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.branco,
    padding: 16,
  },
  topTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.marrom,
    marginLeft: 20,
    marginTop: 6,
    marginBottom: 12,
    letterSpacing: 1,
    textAlign: "center",
  },
  headerCard: {
    alignItems: "center",
    backgroundColor: "#f7e7d7",
    borderRadius: 16,
    paddingVertical: 18,
    marginTop: 22,
    marginBottom: 22,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  emoji: {
    fontSize: 36,
    marginBottom: 4,
  },
  greeting: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.marromEscuro,
    marginBottom: 6,
    textAlign: "center",
  },
  badge: {
    alignSelf: "center",
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 6,
    marginTop: 2,
    marginBottom: -8,
  },
  badgeText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
    letterSpacing: 1,
  },
  boxInfo: {
    backgroundColor: COLORS.cinzaClaro,
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 18,
    marginBottom: 24,
    position: "relative",
    shadowColor: "#000",
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  infoRowNoBorder: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
  },
  label: {
    fontWeight: "bold",
    color: COLORS.marromEscuro,
    fontSize: 16,
    letterSpacing: 0.5,
  },
  value: {
    color: COLORS.marromEscuro,
    fontSize: 16,
    maxWidth: 180,
    textAlign: "right",
  },
  inputEdit: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#b4a398",
    color: COLORS.marromEscuro,
    fontSize: 16,
    paddingVertical: 2,
    paddingHorizontal: 4,
    minWidth: 120,
    maxWidth: 200,
    backgroundColor: "#f9f4ef",
    borderRadius: 6,
  },
  changePwdBtn: {
    flexDirection: "row",
    backgroundColor: "#9c7950",
    borderRadius: 8,
    alignItems: "center",
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingVertical: 8,
    marginTop: 18,
  },
  changePwdBtnText: {
    color: "#fff",
    fontWeight: "bold",
    marginLeft: 8,
    fontSize: 15,
  },
  editBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#ece1d8",
    borderRadius: 8,
  },
  editBtnText: {
    color: "#60492C",
    fontWeight: "bold",
    marginLeft: 6,
    fontSize: 15,
  },
  saveBtn: {
    backgroundColor: "#3d7a4f",
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: "center",
  },
  saveBtnText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 15,
  },
  cancelBtn: {
    backgroundColor: "#aaa",
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: "center",
  },
  cancelBtnText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 15,
  },
  employeesBlock: {
    marginTop: 16,
    marginBottom: 24,
    padding: 14,
    borderRadius: 10,
    backgroundColor: "#fcf6ef",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  employeesTitle: {
    fontWeight: "bold",
    color: "#9c7950",
    fontSize: 16,
    marginBottom: 8,
  },
  employeesEmpty: {
    fontStyle: "italic",
    color: "#aaa",
    marginTop: 8,
  },
  employeeCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 8,
    marginBottom: 10,
    padding: 10,
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  employeeName: {
    color: "#60492C",
    fontWeight: "bold",
    fontSize: 15,
  },
  employeeEmail: {
    color: "#9c7950",
    fontSize: 13,
  },
  tipsCard: {
    flexDirection: "row",
    backgroundColor: "#e4eefc",
    padding: 16,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 10,
    marginBottom: 30,
  },
  tipsText: {
    color: "#355483",
    fontSize: 15,
    marginLeft: 6,
    flex: 1,
  },
});

export default styles;