import { COLORS, FONT_SIZE } from "../../../constants/tema"

const styles = {
  container: {
    width: "100%",
    flex: 1,
    paddingVertical: 20,
    paddingTop: 60,
    alignItems: "stretch",
    backgroundColor: COLORS.branco,
  },
  scroll: {
    paddingVertical: 10,
    backgroundColor: COLORS.branco,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  line: {
    width: "90%",
    borderColor: COLORS.marrom,
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 1,
    alignSelf: "center",      
  },
  lineT: {
    fontSize: FONT_SIZE.md2,
    color: COLORS.marrom,
  },
  name: {
    fontSize: FONT_SIZE.lg,
    fontWeight: "800",
    color: COLORS.azulEscuro,
  },
  boxInfo: {
    width: "90%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.branco,
    padding: 10,
    paddingLeft: 50,
    paddingRight: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: COLORS.marrom,
  },
  text: {
    fontSize: FONT_SIZE.md,
    fontWeight: "700",
    color: COLORS.marrom,
  },
  text2: {
    fontSize: FONT_SIZE.sm,
    fontWeight: "400",
    color: COLORS.marrom,
  },
  btnInfo: {
    position: "absolute",
    left: 10,
  },
  infoEstante: {
    width: "90%",
    backgroundColor: COLORS.branco,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.marrom,
    padding: 15,
    gap: 10,
    alignItems: "flex-start",
    justifyContent: "center",
    zIndex: 100,
    position: "absolute",
    top: "30%",
  },
  textM: {
    fontSize: FONT_SIZE.md,
    fontWeight: "700",
    color: COLORS.marromClaro,
  },
  labelText: {
    fontSize: FONT_SIZE.md,
    fontWeight: "700",
    color: COLORS.marrom,
  },
  textWrapper: {
    flexDirection: "row",
    marginBottom: 5,
    width: "80%",
  },
  closeButton: {
    position: "absolute",
    top: 10,
    right: 10,
    padding: 10,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  popupButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.marrom,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
}

export default styles